[pytest]
filterwarnings =
    ignore:datetime.datetime.utcnow.*deprecated:DeprecationWarning:mongomock.*
    ignore:Accessing the 'model_fields' attribute on the instance is deprecated.*:pydantic.warnings.PydanticDeprecatedSince211:lazy_model.*
    ignore:Accessing the 'model_fields' attribute on the instance is deprecated.*:pydantic.warnings.PydanticDeprecatedSince211:beanie.*